function waitFor(obj,prop,func,self,count){if(obj[prop]){func.apply(self);}else{count=count||0;if(count<1000)setTimeout(function(){waitFor(obj,prop,func,self,count+1)},0);}}if(!window.FW)window.FW={}
FW.extend=function(target,source,overwrite){for(var key in source){if(overwrite||typeof target[key]==='undefined'){target[key]=source[key];}}return target;};FW.extend(FW,{_assetsVersion:56,_apiEndpoint:'//flowwow.com/widgets/api/index.php',_assetsPath:'/widgets/build/',_iframeSrc:'/widgets/rating.php',_shopId:null,_serverData:null,_ratingButtonText:null});FW.init=function(options){if(!options.shopId){throw Error('FW.init() should be called with shopId');}if(typeof options.ratingButtonText=='string'){FW._ratingButtonText=options.ratingButtonText;}FW._shopId=options.shopId;}
FW.Templates={};FW.Templates.ratingButton=function(){var newBlock=document.createElement('div');newBlock.id='fw-rating-button';newBlock.className='fw-button';newBlock.type='button';newBlock.innerHTML=''+'<div class="fw fw-button-rating">'+FW._serverData.rating+' / 5</div>'+'<div class="fw fw-button-hearts"><b style="width:'+FW._serverData.ratingCssPercent+'%;"></b></div>'+'<div class="fw fw-button-text">'+(FW._ratingButtonText?FW._ratingButtonText:FW._serverData.lang.reviews+'<br>'+FW._serverData.lang.aboutUs)+'</div>'+'';return newBlock;}
FW.Templates.ratingModal=function(){var newBlock=document.createElement('div');newBlock.id='fw-modal-rating';newBlock.className='modal fade';newBlock.style.display='none';var verified=FW._serverData.shopTested?'<div class="fw fw-header-verified">'+'<i class="t" title="'+FW._serverData.lang.shopDelivered+'"></i>'+'</div>':'';newBlock.innerHTML=''+'<div class="fw fw-modal-header">'+'<div class="fw fw-header-logo">'+'<a href="//'+FW._serverData.serverHost+'/shop/'+FW._serverData.shopUrl+'/review/" class="fw fw-logo"></a>'+'</div>'+'<div class="fw fw-header-text">'+FW._serverData.lang.naFlowSobrani+'</div>'+verified+'</div>'+'<div class="fw fw-modal-body">'+'<iframe id="fw-modal-iframe" align="center" frameborder="0" marginheight="0" marginwidth="0" scrolling="yes" style="height: 100%;width:100%;"></iframe>'+'</div>';return newBlock;}
FW.attachCss=function(name,callback){setTimeout(function(){var link=document.createElement('link');link.rel='stylesheet';link.type='text/css';link.href='//'+FW._serverData.serverHost+FW._assetsPath+'css/'+name+'.css?v='+FW._assetsVersion;link.media='all';waitFor(document,'body',function(){document.getElementsByTagName('HEAD')[0].appendChild(link);callback();});},0);}
FW.attachScript=function(name){setTimeout(function(){var needJquery=true;var newScript=document.createElement('script');newScript.type='text/javascript';newScript.src='//'+FW._serverData.serverHost+FW._assetsPath+'js/'+name+(needJquery?'':'-no-jquery')+'.js?v='+FW._assetsVersion;waitFor(document,'body',function(){document.getElementsByTagName('HEAD')[0].appendChild(newScript);});},0);}
FW.Api={};FW.Api.createRequest=function(url){var xhr=new XMLHttpRequest();if("withCredentials"in xhr){xhr.open('GET',url,true);xhr.withCredentials=true;}else if(typeof XDomainRequest!="undefined"){xhr=new XDomainRequest();xhr.open('GET',url);xhr.withCredentials=true;}else{xhr=null;}return xhr;}
FW.Api.makeRequest=function(url,callback){var xhr=FW.Api.createRequest(url);if(!xhr){return false;}xhr.onload=function(){var text=xhr.responseText;if(xhr.status===200){callback(text);}else{try{console.error('Can`t reach API',xhr.response);}catch(e){}}};xhr.onerror=function(){try{console.error('Can`t reach API');}catch(e){}};xhr.send();return true;}
FW.Api.makeModalLink=function(elementId){var element=document.getElementById(elementId);element.dataset.toggle='modal';element.dataset.target='#fw-modal-rating';element.onclick=function(){document.getElementById('fw-modal-iframe').src='//'+FW._serverData.serverHost+FW._iframeSrc+'?shop='+FW._shopId;};}
FW.Widgets={};FW.Widgets.parseRatingData=function(jsonStr){FW._serverData=JSON.parse(jsonStr);FW.attachCss('rating-button',function(){var body=document.getElementsByTagName('BODY')[0],button=FW.Templates.ratingButton();body.appendChild(button);body.appendChild(FW.Templates.ratingModal());FW.Api.makeModalLink(button.id);});FW.attachScript('rating');}
FW.Widgets.Rating=function(){FW.Api.makeRequest(FW._apiEndpoint+'?widget=1&shop='+FW._shopId,FW.Widgets.parseRatingData);}
